"""anonymous_column

Revision ID: 023bed85804f
Revises: 8919ea6363b0
Create Date: 2024-03-22 17:09:25.780588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023bed85804f'
down_revision: Union[str, None] = '8919ea6363b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AnonymousPosts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.Text(), nullable=False),
    sa.Column('post_image', sa.String(), nullable=True),
    sa.Column('posted_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posted_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.add_column('posts', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_anonymous')
    op.drop_table('AnonymousPosts')
    # ### end Alembic commands ###
