"""anonymous_column

Revision ID: 370f1b3cb9f8
Revises: 023bed85804f
Create Date: 2024-03-22 17:12:20.927970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370f1b3cb9f8'
down_revision: Union[str, None] = '023bed85804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_anonymous')
    # ### end Alembic commands ###
