"""“post_update”

Revision ID: 4af13e2fcf3a
Revises: b5113d3effb6
Create Date: 2024-03-11 12:49:34.987215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af13e2fcf3a'
down_revision: Union[str, None] = 'b5113d3effb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
