"""event_id

Revision ID: 6c7fb206d77d
Revises: 9b7d012323ce
Create Date: 2024-03-25 19:27:44.446830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7fb206d77d'
down_revision: Union[str, None] = '9b7d012323ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Events_event_id'), 'Events', ['event_id'], unique=False)
    op.drop_column('Events', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_Events_event_id'), table_name='Events')
    # ### end Alembic commands ###
