"""events_and_org

Revision ID: 8919ea6363b0
Revises: 411ee19a866d
Create Date: 2024-03-22 02:01:03.371276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8919ea6363b0'
down_revision: Union[str, None] = '411ee19a866d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Organizations', 'organization_admins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Organizations', 'organization_admins',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
