"""many_organization_admins

Revision ID: 915b3592607f
Revises: ae1a8ad6b66e
Create Date: 2024-03-25 14:07:30.919314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '915b3592607f'
down_revision: Union[str, None] = 'ae1a8ad6b66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.drop_constraint('Organizations_organization_admins_fkey', 'Organizations', type_='foreignkey')
    op.drop_column('Organizations', 'organization_admins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organizations', sa.Column('organization_admins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Organizations_organization_admins_fkey', 'Organizations', 'Users', ['organization_admins'], ['id'])
    op.drop_table('Organization_admins')
    # ### end Alembic commands ###
