"""event_id

Revision ID: 9b7d012323ce
Revises: 9f600f9241b4
Create Date: 2024-03-25 19:26:42.741371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7d012323ce'
down_revision: Union[str, None] = '9f600f9241b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Events', 'id')
    # ### end Alembic commands ###
