"""organizations_id to event

Revision ID: a98dc9093660
Revises: 915b3592607f
Create Date: 2024-03-25 18:25:17.552711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98dc9093660'
down_revision: Union[str, None] = '915b3592607f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Events', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Events', 'Organizations', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.drop_column('Events', 'organization_id')
    # ### end Alembic commands ###
