"""organizations_id to event

Revision ID: db16a4c9ddc1
Revises: 9c1864827521
Create Date: 2024-03-25 18:51:00.467386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db16a4c9ddc1'
down_revision: Union[str, None] = '9c1864827521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Categories_id'), 'Categories', ['id'], unique=False)
    op.create_table('Events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_text', sa.String(), nullable=False),
    sa.Column('event_photo', sa.String(), nullable=False),
    sa.Column('event_time_creation', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Events_id'), 'Events', ['id'], unique=False)
    op.drop_constraint('Organization_admins_organization_id_fkey', 'Organization_admins', type_='foreignkey')
    op.create_foreign_key(None, 'Organization_admins', 'Organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('Organizations', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_Organizations_organization_id', table_name='Organizations')
    op.create_index(op.f('ix_Organizations_id'), 'Organizations', ['id'], unique=False)
    op.drop_column('Organizations', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organizations', sa.Column('organization_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Organizations_organization_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_Organizations_id'), table_name='Organizations')
    op.create_index('ix_Organizations_organization_id', 'Organizations', ['organization_id'], unique=False)
    op.drop_column('Organizations', 'id')
    op.drop_constraint(None, 'Organization_admins', type_='foreignkey')
    op.create_foreign_key('Organization_admins_organization_id_fkey', 'Organization_admins', 'Organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_Events_id'), table_name='Events')
    op.drop_table('Events')
    op.drop_index(op.f('ix_Categories_id'), table_name='Categories')
    op.drop_table('Categories')
    # ### end Alembic commands ###
