"""some_changes

Revision ID: dc2d183dedfd
Revises: e0966afd6523
Create Date: 2024-03-25 19:05:05.303861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc2d183dedfd'
down_revision: Union[str, None] = 'e0966afd6523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organization_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    op.drop_index('ix_Categories_category_id', table_name='Categories')
    op.add_column('Events', sa.Column('event_id', sa.Integer(), nullable=False))
    op.add_column('Events', sa.Column('event_text', sa.String(), nullable=False))
    op.add_column('Events', sa.Column('event_photo', sa.String(), nullable=False))
    op.add_column('Events', sa.Column('event_time_creation', sa.DateTime(), nullable=False))
    op.add_column('Events', sa.Column('event_date', sa.Date(), nullable=False))
    op.add_column('Events', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_index('ix_Events_id', table_name='Events')
    op.create_foreign_key(None, 'Events', 'Organizations', ['organization_id'], ['organization_id'])
    op.drop_column('Events', 'text')
    op.drop_column('Events', 'photo')
    op.drop_column('Events', 'time_creation')
    op.drop_column('Events', 'id')
    op.add_column('Organizations', sa.Column('organization_desc', sa.Text(), nullable=True))
    op.drop_index('ix_Organizations_organization_id', table_name='Organizations')
    op.drop_constraint('Organizations_organization_admins_fkey', 'Organizations', type_='foreignkey')
    op.drop_column('Organizations', 'organization_admins')
    op.add_column('Users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_anonymous')
    op.drop_column('Users', 'bio')
    op.add_column('Organizations', sa.Column('organization_admins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Organizations_organization_admins_fkey', 'Organizations', 'Users', ['organization_admins'], ['id'])
    op.create_index('ix_Organizations_organization_id', 'Organizations', ['organization_id'], unique=False)
    op.drop_column('Organizations', 'organization_desc')
    op.add_column('Events', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Events_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('Events', sa.Column('time_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Events', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Events', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.create_index('ix_Events_id', 'Events', ['id'], unique=False)
    op.drop_column('Events', 'organization_id')
    op.drop_column('Events', 'event_date')
    op.drop_column('Events', 'event_time_creation')
    op.drop_column('Events', 'event_photo')
    op.drop_column('Events', 'event_text')
    op.drop_column('Events', 'event_id')
    op.create_index('ix_Categories_category_id', 'Categories', ['category_id'], unique=False)
    op.drop_table('Organization_admins')
    # ### end Alembic commands ###
