"""event_delete

Revision ID: e0966afd6523
Revises: e205c7d48b10
Create Date: 2024-03-25 18:59:02.293600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0966afd6523'
down_revision: Union[str, None] = 'e205c7d48b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_text', sa.String(), nullable=False),
    sa.Column('event_photo', sa.String(), nullable=False),
    sa.Column('event_time_creation', sa.DateTime(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.category_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    # ### end Alembic commands ###
