"""event_delete

Revision ID: e205c7d48b10
Revises: eb73d206024d
Create Date: 2024-03-25 18:58:35.406962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e205c7d48b10'
down_revision: Union[str, None] = 'eb73d206024d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Events',
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Events_event_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('event_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_photo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_time_creation', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Categories.category_id'], name='Events_category_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], name='Events_organization_id_fkey'),
    sa.PrimaryKeyConstraint('event_id', name='Events_pkey')
    )
    # ### end Alembic commands ###
