"""id_change

Revision ID: eb73d206024d
Revises: 8b4dbc61324f
Create Date: 2024-03-25 18:54:25.640602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb73d206024d'
down_revision: Union[str, None] = '8b4dbc61324f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Events_event_id', table_name='Events')
    op.drop_index('ix_Organizations_organization_id', table_name='Organizations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Organizations_organization_id', 'Organizations', ['organization_id'], unique=False)
    op.create_index('ix_Events_event_id', 'Events', ['event_id'], unique=False)
    # ### end Alembic commands ###
