"""event_id

Revision ID: ed49113e25d3
Revises: 6c7fb206d77d
Create Date: 2024-03-25 19:32:05.062193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed49113e25d3'
down_revision: Union[str, None] = '6c7fb206d77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Categories', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Categories', 'category_id')
    op.add_column('Events', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_Events_event_id', table_name='Events')
    op.drop_constraint('Events_category_id_fkey', 'Events', type_='foreignkey')
    op.drop_constraint('Events_organization_id_fkey', 'Events', type_='foreignkey')
    op.create_foreign_key(None, 'Events', 'Categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'Events', 'Organizations', ['organization_id'], ['id'])
    op.drop_column('Events', 'event_id')
    op.drop_constraint('Organization_admins_organization_id_fkey', 'Organization_admins', type_='foreignkey')
    op.create_foreign_key(None, 'Organization_admins', 'Organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('Organizations', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Organizations', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organizations', sa.Column('organization_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Organizations_organization_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('Organizations', 'id')
    op.drop_constraint(None, 'Organization_admins', type_='foreignkey')
    op.create_foreign_key('Organization_admins_organization_id_fkey', 'Organization_admins', 'Organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.add_column('Events', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.drop_constraint(None, 'Events', type_='foreignkey')
    op.create_foreign_key('Events_organization_id_fkey', 'Events', 'Organizations', ['organization_id'], ['organization_id'])
    op.create_foreign_key('Events_category_id_fkey', 'Events', 'Categories', ['category_id'], ['category_id'])
    op.create_index('ix_Events_event_id', 'Events', ['event_id'], unique=False)
    op.drop_column('Events', 'id')
    op.add_column('Categories', sa.Column('category_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Categories_category_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_column('Categories', 'id')
    # ### end Alembic commands ###
