"""organizations_id to event

Revision ID: f80485cd9983
Revises: 3f4a6bf1b471
Create Date: 2024-03-25 18:52:19.331366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80485cd9983'
down_revision: Union[str, None] = '3f4a6bf1b471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('category_image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Categories_id'), 'Categories', ['id'], unique=False)
    op.drop_table('Organization_admins')
    op.add_column('Organizations', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_Organizations_organization_id', table_name='Organizations')
    op.create_index(op.f('ix_Organizations_id'), 'Organizations', ['id'], unique=False)
    op.drop_column('Organizations', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organizations', sa.Column('organization_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Organizations_organization_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_Organizations_id'), table_name='Organizations')
    op.create_index('ix_Organizations_organization_id', 'Organizations', ['organization_id'], unique=False)
    op.drop_column('Organizations', 'id')
    op.create_table('Organization_admins',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], name='Organization_admins_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Organization_admins_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', name='Organization_admins_pkey')
    )
    op.drop_index(op.f('ix_Categories_id'), table_name='Categories')
    op.drop_table('Categories')
    # ### end Alembic commands ###
