"""“remove_following”

Revision ID: 7a2f3a33d9e1
Revises: 44b7bf1d4891
Create Date: 2024-03-13 10:48:02.687082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2f3a33d9e1'
down_revision: Union[str, None] = '44b7bf1d4891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Following')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Following',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['Users.id'], name='Following_follower_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], name='Following_user_id_fkey')
    )
    # ### end Alembic commands ###
