"""“test_commit”

Revision ID: 7d1b6ae2be2e
Revises: ad4bf09d1cf6
Create Date: 2024-03-13 11:54:40.048993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1b6ae2be2e'
down_revision: Union[str, None] = 'ad4bf09d1cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
