"""“user_update_1”

Revision ID: b5113d3effb6
Revises: 05572a846b4c
Create Date: 2024-03-10 15:36:52.175026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5113d3effb6'
down_revision: Union[str, None] = '05572a846b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'avatar')
    # ### end Alembic commands ###
