"""“remove_following”

Revision ID: b7b90f8a2a1d
Revises: 7a2f3a33d9e1
Create Date: 2024-03-13 11:22:38.410896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b90f8a2a1d'
down_revision: Union[str, None] = '7a2f3a33d9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
